Update DesktopXephyr

diff --git a/DesktopXephyr b/DesktopXephyr
--- a/DesktopXephyr
+++ b/DesktopXephyr
@@ -173,60 +173,97 @@ nano Dockerfile
 
 
 
+
 FROM debian:buster
 
-ENV LANG=en_GB.UTF-8
-ENV TZ=Europe/London
+ENV DEBIAN_FRONTEND=noninteractive
 
-RUN \
-  apt-get update && \
-  DEBIAN_FRONTEND=noninteractive \
-  apt-get -fy -o Dpkg::Options::="--force-confnew" \
-    -o APT::Immediate-Configure=false \
-    dist-upgrade && \
-  DEBIAN_FRONTEND=noninteractive \
-  apt-get install -y --no-install-recommends \
-    base-files vim ntp locales apt-transport-https curl \
-    lxde lxde-settings-daemon lxlock lxmusic desktop-base \
-    synaptic libnss-mdns thunderbird inkscape pidgin \
-    gimp gimp-help-en transmission-gtk tracker-miner-fs \
-    avahi-utils avahi-discover firefox-esr-l10n-en-gb \
-    vlc mesa-utils thunderbird-l10n-en-gb libpam-kwallet4 \
-    remmina remmina-common remmina-plugin-rdp \
-    remmina-plugin-vnc remmina-plugin-nx libpam-kwallet5 \
-    remmina-plugin-spice remmina-plugin-xdmcp sudo \
-    geany libcanberra-pulse pulseaudio-module-bluetooth paprefs \
-    pavucontrol gstreamer1.0-pulseaudio cups-pk-helper \
-    pulseaudio-module-zeroconf cups system-config-printer \
-    lightdm slick-greeter dbus-x11 && \
-  rm /etc/apt/apt.conf.d/docker-gzip-indexes && \
-  rm -rf /var/lib/apt/lists/* && apt-get update && \
-  sed -i "s/^# *\($LANG\)/\1/" /etc/locale.gen && \
-  locale-gen && \
-  echo $TZ > /etc/timezone && \
-  ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
-  DEBIAN_FRONTEND=noninteractive dpkg-reconfigure tzdata && \
-  rm /usr/share/xsessions/lightdm-xsession.desktop && \
-  rm /usr/share/xsessions/openbox.desktop && \
-  echo '#!/bin/bash\nexport XAUTHORITY=/root/.Xauthority.docker\nexport DISPLAY=:0\nexec Xephyr $1 -ac -dpi 48 >> /var/log/lightdm/x-1.log' > /usr/bin/Xephyr-lightdm-wrapper && \
-  chmod +x /usr/bin/Xephyr-lightdm-wrapper && \
-  echo '[LightDM]\nminimum-display-number=1\n[Seat:*]\nsession-setup-script=sh -c "xdpyinfo | grep -q RANDR && exec xrandr --output default --mode 1600x1200 || true"\ngreeter-hide-users=false\nxserver-command=/usr/bin/Xephyr-lightdm-wrapper' > /etc/lightdm/lightdm.conf && \
-  rm -f /etc/systemd/system/display-manager.service && \
-  ln -s /lib/systemd/system/lightdm.service /etc/systemd/system/display-manager.service && \
-  echo '/usr/sbin/lightdm' > /etc/X11/default-display-manager && \
-  echo '[Greeter]\nbackground=/usr/share/desktop-base/futureprototype-theme/plymouth/plymouth_background_future.png\n' > /etc/lightdm/slick-greeter.conf && \
-  echo 'XKBMODEL="pc105"\nXKBLAYOUT="gb"\nXKBVARIANT=""\nXKBOPTIONS=""' > /etc/default/keyboard && \
-  echo "console-setup console-setup/charmap select UTF-8" | debconf-set-selections && \
-  sed -i 's/Dir::Cache::pkgcache "";//' /etc/apt/apt.conf.d/docker-clean && \
-  rm -f /etc/systemd/system/getty.target.wants/getty@tty1.service && \
-  sed -i 's/#DefaultTimeoutStopSec=90s/DefaultTimeoutStopSec=5s/' /etc/systemd/system.conf && \
-  chmod 755 /etc/polkit-1/localauthority && \
-  echo "[Shutdown & Restart]\nIdentity=unix-user:*\nAction=org.freedesktop.login1.power-off;org.freedesktop.login1.power-off-multiple-sessions;org.freedesktop.login1.reboot;org.freedesktop.login1.reboot-multiple-sessions\nResultAny=yes\nResultInactive=yes\nResultActive=yes\n" > /etc/polkit-1/localauthority/50-local.d/10-shutdown.pkla
+# Replace old repositories with archive.debian.org and allow expired metadata
+RUN echo "deb http://archive.debian.org/debian buster main contrib non-free" > /etc/apt/sources.list && \
+    echo "deb http://archive.debian.org/debian-security buster/updates main" >> /etc/apt/sources.list && \
+    echo 'Acquire::Check-Valid-Until "false";' > /etc/apt/apt.conf.d/99no-check-valid-until && \
+    apt-get update && \
+    apt-get install -y --no-install-recommends \
+        dbus-x11 lightdm slick-greeter \
+        lxde lxterminal lxsession lxappearance lxinput lxrandr \
+        synaptic policykit-1 x11-xserver-utils \
+        locales tzdata xinit xserver-xephyr \
+        systemd systemd-sysv sudo console-setup \
+        desktop-base \
+        x11-utils x11-xkb-utils xfonts-base x11-xfs-utils \
+        x11-common x11-session-utils x11-xkb-utils \
+        gnome-icon-theme gnome-themes-standard \
+        pulseaudio alsa-utils \
+        mousepad \
+    && apt-get clean
+
+# Fix Synaptic slowness (due to Docker compressing index files)
+RUN rm /etc/apt/apt.conf.d/docker-gzip-indexes
+
+# Set locale and timezone
+RUN echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && \
+    locale-gen && \
+    ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime && \
+    dpkg-reconfigure -f noninteractive tzdata
+
+# Remove conflicting .desktop files to ensure correct LightDM session
+RUN rm -f /usr/share/xsessions/lightdm-xsession.desktop /usr/share/xsessions/openbox.desktop
+
+# Xephyr LightDM wrapper script
+RUN echo '#!/bin/bash\n\
+export XAUTHORITY=/root/.Xauthority.docker\n\
+export DISPLAY=:0\n\
+exec Xephyr $1 -ac -dpi 48 >> /var/log/lightdm/x-1.log' > /usr/bin/Xephyr-lightdm-wrapper && \
+    chmod +x /usr/bin/Xephyr-lightdm-wrapper
+
+# Configure LightDM to use Xephyr
+RUN echo '[LightDM]\n\
+minimum-display-number=1\n\
+[Seat:*]\n\
+session-setup-script=sh -c "xdpyinfo | grep -q RANDR && exec xrandr --output default --mode 1600x1200 || true"\n\
+greeter-hide-users=false\n\
+xserver-command=/usr/bin/Xephyr-lightdm-wrapper' > /etc/lightdm/lightdm.conf
+
+# Set LightDM as systemd default display manager
+RUN rm -f /etc/systemd/system/display-manager.service && \
+    ln -s /lib/systemd/system/lightdm.service /etc/systemd/system/display-manager.service && \
+    echo '/usr/sbin/lightdm' > /etc/X11/default-display-manager
+
+# Set greeter background to Debian theme
+RUN echo '[Greeter]\n\
+background=/usr/share/desktop-base/futureprototype-theme/plymouth/plymouth_background_future.png' > /etc/lightdm/slick-greeter.conf
+
+# Configure console font and character set
+RUN echo "console-setup console-setup/charmap select UTF-8" | debconf-set-selections
+
+# Fix Synaptic error "_cache->open() failed"
+RUN sed -i 's/Dir::Cache::pkgcache "";//' /etc/apt/apt.conf.d/docker-clean || true
+
+# Disable getty on tty1 (quicker boot, avoids session errors)
+RUN rm -f /etc/systemd/system/getty.target.wants/getty@tty1.service
+
+# Speed up shutdown by reducing systemd timeout
+RUN sed -i 's/#DefaultTimeoutStopSec=90s/DefaultTimeoutStopSec=5s/' /etc/systemd/system.conf
+
+# Allow container sessions to shutdown/reboot
+RUN chmod 755 /etc/polkit-1/localauthority && \
+    echo '[Shutdown & Restart]\n\
+Identity=unix-user:*\n\
+Action=org.freedesktop.login1.power-off;org.freedesktop.login1.power-off-multiple-sessions;org.freedesktop.login1.reboot;org.freedesktop.login1.reboot-multiple-sessions\n\
+ResultAny=yes\n\
+ResultInactive=yes\n\
+ResultActive=yes' > /etc/polkit-1/localauthority/50-local.d/10-shutdown.pkla
+
+CMD ["/sbin/init"]
+
 
 
 
 
 docker build -t debian-lxde:buster .
+
+
+
 
 
 
